services:
  api-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Montiamo la cartella corrente (.) dentro /app nel container
      # Questo permette all'hot-reload di funzionare quando modifichi il codice
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped